app:
  id: read-only_web
  name: Read Only HTTP Server
  log-level: trace

http:
  ip: 0.0.0.0
  port: 334
  cors:
    allowed-methods: ["GET"]
    # allowed-origins:
    # - "https://localhost:8080"
    allowed-headers:
      - "Content-Type"

postgresql:
  host: 0.0.0.0
  port: "5437"
  username: reader
  database: main
  password: 031501

template:
  path: /internal/templates/
